### ISSUE TITLE
Add std::set::Set & friends

### ISSUE THREAD

**Issue by yorickpeterse** [inko-lang/inko#217]
In GitLab by @jc00ke on Sep 10, 2018, 05:07

## Summary

The `Set` construct is a valuable and underused type in some popular programming languages. Ruby, for example, has `Set` and `OrderedSet` but I rarely see them used.

## Motivation

Many times I've run into code that treats an `Array` as if it were a `Set`. I believe that, if `Set` is made available and preferred for cases where it's appropriate, then it will nudge language users to use it.

I also really like the idea of `RestrictedSet` (which has been commented out in Ruby's `set.rb` for who-knows-how-many-years) because it encapsulates the conditional insertion better than piecemeal conditionals or delegation in a custom class.

## Implementation

I would implement it a lot like RubySL's. I think that implementation is relatively straightforward.

## Drawbacks

The only reason I could see to keep this out of `std` is if you think it's better as an add-on package. Otherwise, I think it's a nice type to have around.

## Related work

*  Ruby's [Set](https://github.com/rubysl/rubysl-set/blob/be14c6cbf815f915307b9bd75d46c3a569887bb5/lib/rubysl/set/set.rb)
*  Rust's [HashSet](https://doc.rust-lang.org/std/collections/struct.HashSet.html)
*  Rust's [BTreeSet](https://doc.rust-lang.org/std/collections/struct.BTreeSet.html)

**Comment by heymhm** [comment]
The current `std.set.Set` is a wrapper over `Map[Int, Bool]`, where the boolean value is always `true`. Wouldn't it make more sense for `Set` to wrap `Map[Int, Nil]`? This also aligns well with the docs, where `Nil` is claimed to be Inko's unit type.

For instance, the following works just fine:

```inko
let mut set: Map[Int, Nil] = Map.new
set.set(1, nil)
set.contains?(1)
```

**Comment by yorickpeterse** [comment]
@heymhm Using `Nil` would work equally well and would be fine, though in terms of memory usage it won't make a difference as both `Bool` and `Nil` are represented as a single byte (well technically a single bit, but LLVM rounds those up to a single byte).

**Comment by heymhm** [comment]
> in terms of memory usage it won't make a difference as both Bool and Nil are represented as a single byte

I agree, but still, Map[V, Nil] expresses the intent more clearly than Map[V, Bool].
