### ISSUE TITLE
Consider changing Option.unwrap to throw instead of panicking

### ISSUE THREAD

**Issue by yorickpeterse** [inko-lang/inko#512]
### Description

`Option.unwrap` panics when used on a `None`. Should we decide to stick with throwing errors (see https://github.com/inko-lang/inko/issues/362 for more details on that), it might be worth changing this method to throw instead. This way one can write `try some_option.unwrap else ...` instead of the more verbose `match some_option { case Some(v) -> v, case _ -> ... }`. This also gives the user more control over when/where to panic, instead of the standard library making that decision for you.

Should we decide to drop throws in favour of `Result` types, then we should just keep the panic as there's no sane alternative in such a setup.

**Comment by dusty-phillips** [comment]
I'd be happy with two methods -- `unwrap_or_panic()` for the case where the developer expects a value to exist, and `unwrap_or_throw(thing_to_throw)` for the case where they want to throw an exception.
