### ISSUE TITLE
Links in docs website point to GitLab repo which is marked as archived

### ISSUE THREAD

**Issue by tupini07** [inko-lang/inko#518]
Hello! I was going through the documentation (https://docs.inko-lang.org/) to learn a bit more about the language and noticed that all links pointing "the source" are sending me to GitLab, but there I see that the repo has been archived and the official repo is now this one (on github). Should the links be changed? 

These are the ones I noticed but there might be more:

- in the footer
- at the top right
- in [Home](https://docs.inko-lang.org/manual/master/)
- Link to [vim plugin](https://docs.inko-lang.org/manual/master/getting-started/editors/#vimneovim) in editor integration page
- Link to [ivm](https://docs.inko-lang.org/manual/master/getting-started/ivm/)
- Not sure if this is something to change as well but in [Docker installation](https://docs.inko-lang.org/manual/master/getting-started/installation/#docker) it says docker images are published on gitlab 

I was going to make a small PR to fix the links I saw but then opted for creating an issue since I'm not sure if they should be changed to point to the github repo or not :P

**Comment by yorickpeterse** [comment]
@tupini07 What link to the documentation are you using? If you are using https://docs.inko-lang.org/manual/master/index.html then indeed the links are old, as that's based on the old `master` branch from before moving back to GitHub. Simply using https://docs.inko-lang.org/ should point you to https://docs.inko-lang.org/manual/main/index.html, which should have all the correct links.

**Comment by tupini07** [comment]
ohh I see! thanks. So it seems then that the link I followed in the README to [Installing inko](https://github.com/inko-lang/inko#installing) is pointing to the old doc site and that's why I was seeing all the wrong links :P

**Comment by yorickpeterse** [comment]
@tupini07 Ah you're right, that still links to `master` instead of `main`. I'll fix that, thanks!
