### ISSUE TITLE
Replace use of the libc crate with the rustix crate

### ISSUE THREAD

**Issue by yorickpeterse** [inko-lang/inko#521]
### Description

https://github.com/inko-lang/inko/pull/508 introduces a native code compiler uses LLVM, replacing the bytecode interpreter. As part of this work we've dropped Windows support, as it's simply not sustainable for us to support.

For network IO we use the [polling](https://github.com/smol-rs/polling) crate. Currently this crate uses libc on Unix platforms, but is switching to using [rustix](https://github.com/bytecodealliance/rustix) (see https://github.com/smol-rs/polling/pull/108).

In the interest of reducing third-party dependencies and maintaining control over our code, I would not only like to restore our old polling code in favour of the "polling" crate (https://github.com/inko-lang/inko/issues/344), but also switch to using rustix. The benefit of using rustix is that at least on Linux we can avoid libc calls. While this _may_ result in a performance improvement, it's really more about slowly reducing our dependencies on third-party libraries, including libc. The API might also be a bit more pleasant to use compared to using the libc crate directly.

### Related work

https://github.com/smol-rs/polling/pull/108

**Comment by thaodt** [comment]
hi @yorickpeterse can you please assign this to me? I wanna give it a try.

**Comment by yorickpeterse** [comment]
Fixed by https://github.com/inko-lang/inko/pull/582.
