### ISSUE TITLE
Add/improve documentation about non-blocking IO

### ISSUE THREAD

**Issue by yorickpeterse** [inko-lang/inko#535]
The documentation doesn't clearly describe what Inko does with (non)blocking IO. There's a brief overview in the [internals section](https://docs.inko-lang.org/manual/main/internals/runtime/#io-operations), but that's not the first place people would look. We should add a page in the "Getting started" section that covers this in greater detail, along with some examples on how to use files and sockets.

**Comment by itsajay1029** [comment]
I'd love to work on this @yorickpeterse Pls assign it to me

**Comment by yorickpeterse** [comment]
@itsajay1029 Have you taken a look at how Inko handles this/how familiar are you with this part of Inko? The documentation wouldn't just consist of moving the chunk from the internals page to a separate one, but also a more in depth explanation, some examples of the standard library code to use, etc. If you're familiar with that (or willing to spend time digging into that) then that would be great, but otherwise it may be better if I do it at some point :smiley:

**Comment by itsajay1029** [comment]
I am willing to dig deep and do it myself. If you can guide me on what resources I should use for learning more about it @yorickpeterse

**Comment by yorickpeterse** [comment]
@itsajay1029 Ehm, the resource is this very repository? Learning more would require digging into the runtime library, how it's used from the standard library, etc. Your best bet would be to read the existing documentation to learn more about Inko, then take a look at the standard library and the rest.

While the issue has the "accepting contributions" label, that doesn't necessarily mean everything is clearly laid out and no extra work is necessary, it just means I'm open to contributions from others. As such, unless you're willing to commit a decent amount of time now and in the future to Inko (otherwise it's just a waste to dig into it), it might be best to leave this issue be.
