### ISSUE TITLE
Add warnings for unused local variables

### ISSUE THREAD

**Issue by yorickpeterse** [inko-lang/inko#543]
### Description

If a variable is defined but never referred to, the compiler should emit a warning about this.

The implementation would be as follows:

- `types::Variable` is given a `used` field that defaults to `false`
- When type checking `let` definitions, we record the `Variable` and its source location in the surrounding method
- When resolving a local variable to its `VariableId`, we set `used` for that `VariableId`/`Variable` to `true`
- At the end of the method we iterate over the tracked variables, emitting a warning for those where `used` is still set to `false`
- Variables that are `_` or start with `_` are ignored (e.g. `let _foo = x` doesn't emit warnings)

This is done at the type checking layer (`compiler::type_check::Expressions`).

**Comment by thaodt** [comment]
hi @yorickpeterse this task looks interesting. I want to tackle it. Could you please assign it to me? :smiley:

**Comment by yorickpeterse** [comment]
@thaodt Sure! Thanks for looking into this :smile:

**Comment by thaodt** [comment]
hi @yorickpeterse sorry for long delay, I've just cleaned up some personal work and still interested in this. Could you please assign to me again? :pray:

**Comment by yorickpeterse** [comment]
@thaodt Sure! :smiley:
