### ISSUE TITLE
Document that one should avoid updating a value destructured as part of a match expression

### ISSUE THREAD

**Issue by yorickpeterse** [inko-lang/inko#546]
A pattern one may find themselves running into is this:

```inko
match @some_field {
  case Some(thing) -> @some_field = Option.Some(bla)
  ...
}
```

That is: they match against some reference stored in a variable or field, destructure it, then update the variable/field with a new value. The problem here is that the reference to `thing` lives until the end of the `case` body, _after_ `@some_field` is assigned a new value. At runtime this results in a panic, as the assignment would otherwise drop a value that still has references to it.

There's currently no way we can reliably catch this at compile time, so instead we should document this in https://docs.inko-lang.org/manual/main/getting-started/pattern-matching/#ownership-and-moves. This should include an example that triggers the panic, and an example of how to work around that (e.g. moving the update out of the `match`, and having the `case` return the new value or a flag of sorts).

We should also include that it's fine to match against a value that _isn't_ destructured, e.g. this is totally fine:

```inko
match @some_field {
  case Foo -> @some_field = Thing.Bar
  case Bar -> ...
}
```

This is fine because no references are created to `@some_field` that live until after the assignment.

**Comment by itsajay1029** [comment]
Can you assign this to me @yorickpeterse ? Also, explain the issue

**Comment by yorickpeterse** [comment]
@itsajay1029 The issue description already contains some details, what extra details were you thinking of?

**Comment by itsajay1029** [comment]
I needed to know what I need to add in documantation and under which section it must be added @yorickpeterse

**Comment by yorickpeterse** [comment]
@itsajay1029 If you're not sure what to document then this issue probably isn't suitable to work on. After all, to document something you must have an understanding of it. If I outline everything here I might as well do it myself :smiley:
