### ISSUE TITLE
Statically link against libgcc instead of dynamic linking

### ISSUE THREAD

**Issue by yorickpeterse** [inko-lang/inko#561]
### Description

`cc`, `gcc`, `clang`, and possibly others support the flag `-static-libgcc` to statically link libgcc, instead of dynamically linking it; at least on Linux. This makes it easier to distribute executables. We should use this option automatically on Linux, and adjust the documentation that no extra dependencies need to be installed on the deployment environment.

**Comment by yorickpeterse** [comment]
Alpine/musl may not support/probably doesn't need this flag. The libgcc package on Alpine also only seems to include the `.so` file, not the `.a` file for libgcc.

**Comment by yorickpeterse** [comment]
Arch Linux doesn't seem to include the `.a` file either, yet the flag works just fine. I guess it's pulled in through other means. Either way, I think as long as gcc is installed it should be fine.

**Comment by oliwer** [comment]
On Alpine, `libgcc.a` is part of the [main gcc package](https://pkgs.alpinelinux.org/contents?file=libgcc*&path=&name=gcc&branch=v3.18&repo=main&arch=x86_64). Same on Arch Linux.

The libgcc is independent of the OS/libc. It's safe to use `-static-libgcc` on all Linuxes, BSDs and MacOS, unless you are linking your binary with other libraries which load `libgcc.so` dynamically.

**Comment by yorickpeterse** [comment]
@oliwer Thanks for the info/confirmation! :smiley:
