### ISSUE TITLE
Empty class enum fails without giving appropriate feedback

### ISSUE THREAD

**Issue by dusty-phillips** [inko-lang/inko#569]
### Please describe the bug

It (maybe?) makes sense that it's not legal to have an empty `class enum` with no cases, but the error message is currently rather inexplicable.

### Please list the exact steps necessary to reproduce the bug

Save the following as `repro.inko`
```
class enum EmptyEnum {}

class async Main {
  fn pub async main() {}
}
```
Then run:
`inko run repro.inko`

Error message is:

```
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', compiler/src/llvm/builder.rs:637:35
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
zsh: abort      inko run
```

### Operating system

Macos

### Inko version

Inko main branch as of c21c4b7d163ac80a64f66f37a1c8e584101ccfc9

### Rust version

1.69.0

**Comment by yorickpeterse** [comment]
An enum without any cases doesn't make sense to me, so it seems best to emit a type error in that case. We definitely shouldn't panic like we do now.
