### ISSUE TITLE
Automatically generate the main.inko file for unit tests

### ISSUE THREAD

**Issue by yorickpeterse** [inko-lang/inko#575]
### Description

When writing unit tests, one has to manually create and maintain `test/main.inko`. This is tedious and prone to error, as every new test file must be loaded from this file.

To make this easier, we should generate the contents of this file when running `inko test`. The generated file would be saved in `build/inko-tests.inko`, and the resulting executable in `build/inko-tests` (this is already the case).

To generate this file, we recursively find all files called `test_*.inko` in `test/`. For each such file, we:

1. Add `import path.to.test_module_name.(self as testsN)` where `test_module_name` is the module name (e.g. `test_string`), and `N` a monotonic number starting at 0. This approach is used to ensure modules with the same name (but in different directories) don't conflict with each other
2. Add a `test_module_name.tests(tests)` line in the `main` method
3. Use the same basic "skeleton" as we do now, i.e the `tests.filter = ....` bit and the likes from https://github.com/inko-lang/inko/blob/main/std/test/main.inko

Generating this file always overwrites an existing version of it. The order of the lines isn't relevant and is unspecified, as tests are run in random order anyway.

The generated file shouldn't be removed after running the tests, as this allows users to inspect it in case of any errors.

And don't forget to update the documentation where relevant.

**Comment by bartlomieju** [comment]
Hey ✋ this seems like a reasonable first contributions. I'll take a stab at it.

**Comment by yorickpeterse** [comment]
@bartlomieju Sure thing, thanks!
