### ISSUE TITLE
`uni` value can be moved multiple times

### ISSUE THREAD

**Issue by jhburns** [inko-lang/inko#588]
### Please describe the bug

A `uni` can be moved multiple times. This is possible by moving a value into a method call while it is also being moved as the method argument.

In addition, when the value is dropped it will recursively call `drop` on itself forever.

### Please list the exact steps necessary to reproduce the bug

Run this code
```ruby
import std::stdio::STDOUT
import std::drop::(Drop)

class Nat {
  let @next: Option[uni Nat]

  fn static new -> Nat {
    Nat { @next = Option.None }
  }

  fn move update(other: uni Nat) {
    @next = Option.Some(other)
  }
}

impl Drop for Nat {
  fn mut drop {
    let out = STDOUT.new

    out.print("dropped")
  }
}

class async Main {
  fn async main {
    let n = recover Nat.new
    n.update(n)
  }
}
```

Note that it typechecks and prints `dropped` a bunch of times.
Frequency: happens every time.  

### Operating system

Ubuntu

### Inko version

0.12

### Rust version

1.68.0

**Comment by yorickpeterse** [comment]
As a note to future self, the solution here is probably as follows:

Given the expression `x.y(x)`, if `y` moves `x`, we should mark `x` as moved _before_ checking the arguments. This way you can't pass `x` as an argument and thus move `x` into itself.
