### ISSUE TITLE
Run CI on ARM64

### ISSUE THREAD

**Issue by yorickpeterse** [inko-lang/inko#614]
As part of the 0.13.0 release (https://github.com/inko-lang/inko/issues/613) I encountered a build failure when building Inko on ARM64 for Fedora (https://download.copr.fedorainfracloud.org/results/yorickpeterse/inko/fedora-37-aarch64/06525817-inko/builder-live.log.gz). The failure was due to the following error:

```
   Compiling socket2 v0.5.3
error[E0308]: mismatched types
  --> rt/src/runtime.rs:62:38
   |
62 |             args.push(CStr::from_ptr(*ptr).to_string_lossy().into_owned());
   |                       -------------- ^^^^ expected `*const u8`, found `*const i8`
   |                       |
   |                       arguments to this function are incorrect
   |
   = note: expected raw pointer `*const u8`
              found raw pointer `*const i8`
note: associated function defined here
  --> /builddir/build/BUILD/rustc-1.72.1-src/library/core/src/ffi/c_str.rs:260:25
```

We currently only run CI on x86-64. I experimented a bit with running the FreeBSD tests on ARM64, but this resulted in IP errors as described in https://github.com/cross-platform-actions/action/issues/63. Using qemu is possible, but this will likely be very slow.

GitHub is adding support for M1 runners (https://github.com/github/roadmap/issues/528), but currently these are only available as large runners that you have to pay for. It's not clear if/when these will be available for FOSS projects. Ideally we just use whatever GitHub offers, but for now it seems there are no good solutions.

**Comment by yorickpeterse** [comment]
A temporary approach to just build the runtime library is the following:

```
rustup traget add aarch64-unknown-linux-gnu
cargo build -p rt --target aarch64-unknown-linux-gnu
```

A regular `cargo build` won't work, as cross-compiling LLVM seems to require more work.

**Comment by chenrui333** [comment]
side note, the homebrew arm build actually goes out fine, https://github.com/Homebrew/homebrew-core/pull/150895

**Comment by yorickpeterse** [comment]
https://github.com/inko-lang/inko/actions/runs/6523844533/job/17714887627 failed with the following:

```
   info: downloading installer
  curl: (22) The requested URL returned error: 404
  rustup: installer for platform 'aarch64-unknown-freebsd' not found, this may be unsupported
```

I guess we'd have to use whatever version of Rust is provided by FreeBSD, though this results in FreeBSD tests running a different version from other platforms, which isn't great.

**Comment by yorickpeterse** [comment]
Per b316dfb30aa7d73b43fe17e134841337d6a19d3b we run macOS tests on both AMD64 and ARM64. Unfortunately we can't use the M1 runners to also run Linux on ARM64 through virtualization, as the M1 runners don't support nested virtualization. For the time being this setup should be sufficient though.
