### ISSUE TITLE
Add Path.extension to return the file extension (if any) from a Path

### ISSUE THREAD

**Issue by yorickpeterse** [inko-lang/inko#621]
### Description

We should add the method `extension` to `std.fs.path.Path`, returning an `Option[String]` that contains the extension of the file, if any is present. The leading dot should _not_ be included, such that for a file `foo.inko`, the returned value is `Option.Some('inko')`. Some examples:

| Path          | Output
|:--------------|:-------
| `foo`         | `Option.None`
| `.foo`        | `Option.None`
| `.foo.txt`    | `Option.Some('txt')`
| `foo.txt`     | `Option.Some('txt')`
| `foo.bar.txt` | `Option.Some('txt')`

For the implementation we can use the `bytes_before_last_separator` helper method to find the index of the last separator. If there is any, we then use `String.byte_index` to find the index of the first `.` after said index. We can then slice the path string from said index + 1 to the end of the string. If the file name starts with a `.`, we need to make sure we move the index beyond it, such that `.foo` yields no extension name.

### Related work

- https://doc.rust-lang.org/std/path/struct.Path.html#method.extension

**Comment by uasi** [comment]
> `foo.bar.txt` | `Option.Some('bar.txt')`

This output should be `Option.Some('txt')` if we align our `Path.extension` with Rust's `Path::extension`.

**Comment by yorickpeterse** [comment]
@uasi Good catch, you're right :smile:
