### ISSUE TITLE
ExclusiveRange.step_by produces invalid ranges

### ISSUE THREAD

**Issue by yorickpeterse** [inko-lang/inko#627]
### Please describe the bug

`ExclusiveRange.step_by` yields `ExclusiveRange` values, but the end values of the range are treated as inclusive values, i.e. `0.until(9).step_by(4)` produces the same range bounds as `0.to(9)`, except for the last range where the end value _is_ an exclusive value (= 9 in this case).

Instead of `Range.step_by` being a required method, it should be a default method. Instead of producing `Stream[Range]`, it returns `Stream[InclusiveRange]`. We should then make sure the bounds for each produced range are valid for both inclusive and exclusive ranges.

### Please list the exact steps necessary to reproduce the bug

```inko
import std.stdio.STDOUT

class async Main {
  fn async main {
    STDOUT.new.print('# 0.to(9).step_by(4)')
    0.to(9).step_by(4).each fn (range) {
      STDOUT.new.print("[{range.start}, {range.end}] // {range.size}")
    }

    STDOUT.new.print('# 0.until(9).step_by(4)')
    0.until(9).step_by(4).each fn (range) {
      STDOUT.new.print("[{range.start}, {range.end}) // {range.size}")
    }
  }
}
```

This produces:

```
# 0.to(9).step_by(4)
[0, 3] // 4
[4, 7] // 4
[8, 9] // 2
# 0.until(9).step_by(4)
[0, 3) // 3
[4, 7) // 3
[8, 9) // 1
```

instead it should produce:

```
# 0.to(9).step_by(4)
[0, 3] // 4
[4, 7] // 4
[8, 9] // 2
# 0.until(9).step_by(4)
[0, 3) // 3
[4, 7) // 3
[8, 8) // 1
```

### Operating system

Fedora Silverblue 38

### Inko version

main

### Rust version

1.72.1

**Comment by thaodt** [comment]
does it only happen on Fedora Silverblue 38? Lemme check on mine

**Comment by yorickpeterse** [comment]
@thaodt It's unrelated to the OS, that info is just there because of the default bug report template.
