### ISSUE TITLE
License

### ISSUE THREAD

**Issue by sirinath** [inko-lang/inko#706]
### Description

Is there a possibility to relicense to AL2.0+LLVM Exception & MIT?

**Comment by yorickpeterse** [comment]
@sirinath Is it possible for you to explain _why_ you would like to see that, and why you believe it to be a better choice compared to the MPL 2.0 that's currently used for the Inko ecosystem (i.e. its tooling and some of my packages also use it, which I want to keep consistent)?

Simply asking "Can the license be changed from X to Y" without details isn't useful.

**Comment by yorickpeterse** [comment]
I'm going to close this because:

1. We're not going to change the license
2. No additional details are provided, making this request rather useless
3. OP appears to have a bit of a history of submitting not so helpful issues with little to no details, and I don't want to waste my time on that
