### ISSUE TITLE
Add Tree-sitter grammar

### ISSUE THREAD

**Issue by yorickpeterse** [inko-lang/inko#708]
### Description

This allows a wider range of editors to parse, highlight, etc Inko documents. I'm working on this in https://github.com/inko-lang/tree-sitter-inko.

### Pull requests

NeoVim:
- [x] https://github.com/nvim-treesitter/nvim-treesitter/pull/6549
- [x] ~~https://github.com/neovim/neovim/pull/28597~~
  - [x] Upstream file type detection to Vim first: https://github.com/vim/vim/pull/14699
  - [x] Merge patch according to https://neovim.io/doc/user/dev_vimpatch.html, sort by file type and not extension

Helix: 
- [x] https://github.com/helix-editor/helix/pull/10656
- [x] Mention Helix support in the documentation

### Related work

- https://github.com/nvim-treesitter/nvim-treesitter
- https://github.com/tree-sitter/tree-sitter-rust/blob/master/grammar.js
- https://tree-sitter.github.io/tree-sitter/creating-parsers

**Comment by yorickpeterse** [comment]
https://github.com/inko-lang/tree-sitter-inko implements everything necessary at a base level. https://github.com/nvim-treesitter/nvim-treesitter/pull/6549 adds support for NeoVim, which requires a bunch of NeoVim-specific queries.

For Helix I'm not sure what the process is, but looking at the source code it seems similar to NeoVim in that you have to maintain editor-specific queries.

**Comment by alexaandru** [comment]
FWIW, I have also added your parser to https://github.com/alexaandru/go-sitter-forest so anyone using Go will also be able to make use of it. And with that occasion I discovered this gem of a language, looks really awesome!

**Comment by yorickpeterse** [comment]
@alexaandru Thanks! :smile:

**Comment by alexaandru** [comment]
![inko](https://github.com/inko-lang/inko/assets/85237/a7a1ac8d-74b9-40b4-91f5-155f3adbe3d9)

You might like this - your parser in action, using the Go bindings above mentioned, in my (yet to be open sourced) text editor :-) Cheers!
