### ISSUE TITLE
When running inko pkg sync, a newly downloaded package shouldn't perform a full git clone

### ISSUE THREAD

**Issue by yorickpeterse** [inko-lang/inko#736]
### Description

When a package is downloaded for the first time when running `inko pkg sync`, we run `git clone` to clone the repository. This results in us potentially cloning a lot more than necessary, such as additional branches and tags.

Since we already handle running `git fetch TAG` if the repository is already cloned, we should be able to adjust this by replacing `git clone` with the equivalent of `mkdir NAME`, `git init` and `git remote add origin ...`, followed by a `git fetch`.

In particular, the benefit here is that if a repository includes a `gh-pages` (or similarly large) branch, we don't end up cloning it only to never use it.

**Comment by yorickpeterse** [comment]
See https://github.com/inko-lang/inko/issues/726 for a bit of backstory about this.

**Comment by uasi** [comment]
Wouldn't [`git clone --single-branch`](https://git-scm.com/docs/git-clone#Documentation/git-clone.txt-code--codecodeno-codecodesingle-branchcode) be sufficient?

In a repository cloned this way, we'll only be able to fetch the initially cloned branch. If we need to switch to other branches or tags later, we can ["undo" the single branch mode](https://stackoverflow.com/a/17714718/454997) or [add remote branches one by one](https://stackoverflow.com/a/27860061/454997).

**Comment by yorickpeterse** [comment]
@uasi I think that would in fact require more code compared to the proposal of using `git init` followed by `git fetch`, as we'd only have to change how we clone things, not how we then also fetch/pull new refs.

**Comment by uasi** [comment]
Given that we always do `git fetch --tags` and then checkout a specific tag (and never a branch) when adding/updating a dep,
it wouldn't require any additional steps to fetch new tags within a single branch clone. Let's see how it works.

## Single branch clone

Here, `inko-tmp_fetch_testing.git` has three tags, `v0.0.1`, `v0.0.2`, and `v0.0.3`, and two branches, `master`, and `unneeded`.

```
### Initial checkout

% git clone --single-branch --branch=v0.0.1 https://github.com/uasi/inko-tmp_fetch_testing.git single_branch_clone
Cloning into 'single_branch_clone'...
(snip)
% cd single_branch_clone

# Only the specified tag is fetched
% git branch -r
(empty)
% git tag -l
v0.0.1

# v0.0.1 is already checked out
% git log -n1 --oneline
f8dc746 (HEAD, tag: v0.0.1) Release v0.0.1

### Fetch and checkout a tag

# Fetch all tags
% git fetch --tags
(snip)
 * [new tag]         v0.0.2     -> v0.0.2
 * [new tag]         v0.0.3     -> v0.0.3
% git tag -l
v0.0.1
v0.0.2
v0.0.3

# Remote branches are not fetched
% git branch -r
(empty)

% git checkout v0.0.3
Previous HEAD position was f8dc746 Release v0.0.1
HEAD is now at aaa917c Release v0.0.3 (diverged from v0.0.2)
```

## Full clone (for comparison)

```
### Initial checkout

% git clone https://github.com/uasi/inko-tmp_fetch_testing.git full_clone
Cloning into 'full_clone'...
(snip)

% cd full_clone

# All branches and tags are fetched
% git branch -r
  origin/HEAD -> origin/master
  origin/master
  origin/unneeded
% git tag -l
v0.0.1
v0.0.2
v0.0.3

% git tag checkout v0.0.1
Previous HEAD position was aaa917c Release v0.0.3 (diverged from v0.0.2)
HEAD is now at f8dc746 Release v0.0.1
```

**Comment by uasi** [comment]
>  I think we can get rid of `git fetch --tags` in favour of only fetching the specific tag we request  (based on the requested version).

For pkg add or pkg sync, sure. For pkg update, however, we still need to fetch all tags to find the latest compatible version.

And just to reiterate, `git fetch --tags` won't fetch any branches within a repository cloned with `--single-branch` flag.

**Comment by yorickpeterse** [comment]
@uasi 

Ah yes you're right. In that case we can just leave the `git fetch` as-is and use your single branch approach. I'll take a look at the changes later, thanks! :smiley:
