### ISSUE TITLE
Implement Iter.chain

### ISSUE THREAD

**Issue by rjframe** [inko-lang/inko#747]
### Description

Add a method to chain two iterators together.

Depending on the situation, `chain` would avoid the need to a) process two iterators individually or b) allocate a new array pre-processing.

(I've actually already implemented this so can easily submit a PR)

### Related work

* https://doc.rust-lang.org/std/iter/struct.Chain.html

**Comment by yorickpeterse** [comment]
@rjframe Good idea, this should be easy enough to implement using `std.iter.Stream` :smile:
